// Generates a static pool of ~1000 generic engagement notifications
// (10 categories x 10 openers x 10 closers) at module load time.
const CATEGORIES = [
  {
    key: "chargingTip",
    titles: [
      "Charging Tip",
      "Quick EV Tip",
      "Battery Care 101",
      "Smart Charging",
      "Pro Charging Tip",
      "EV Know-How",
      "Charge Smarter",
      "Battery Health Tip",
      "Tip of the Day",
      "Power Up Tip",
    ],
    openers: [
      "Charging between 20% and 80% keeps your battery healthiest.",
      "Avoid frequent 0% to 100% charges — your battery will thank you.",
      "DC fast charging is great for road trips, but daily AC charging is gentler on your battery.",
      "Preconditioning your battery before a fast charge can speed things up.",
      "Charging overnight at home is often cheaper and easier on your battery.",
      "Extreme heat can slow charging speed — try to charge in shade when possible.",
      "Topping up little and often is usually better than deep discharges.",
      "Check tyre pressure regularly — it affects your EV's real-world range.",
      "Plan charging stops on long trips before your battery drops below 20%.",
      "Use scheduled charging to charge during off-peak electricity hours.",
    ],
    closers: [
      "Small habits like this add years to your battery's life.",
      "It's an easy way to protect your investment.",
      "Your range and battery health will both benefit.",
      "A few simple habits go a long way.",
      "Open the app to find your nearest charger and get started.",
      "Every bit of care now saves money later.",
      "It only takes a moment to build the habit.",
      "Your EV will run smoother for it.",
      "Try it on your next charge.",
      "Small steps, big difference over time.",
    ],
  },
  {
    key: "ecoImpact",
    titles: [
      "Your Green Impact",
      "Eco Milestone",
      "Cleaner Miles",
      "Carbon Saved",
      "Going Green",
      "Planet-Friendly Driving",
      "Your Eco Footprint",
      "Sustainable Driving",
      "Green Miles Update",
      "Eco Win",
    ],
    openers: [
      "Every mile you drive electric means fewer emissions on the road.",
      "Switching to EV charging is one of the simplest ways to cut your carbon footprint.",
      "Cleaner air starts with choices like the one you made going electric.",
      "Your EV is quietly doing its part for cleaner cities.",
      "Charging up means one less trip to a fuel pump — and cleaner air for everyone.",
      "Driving electric today helps reduce tomorrow's emissions.",
      "Your daily commute is now part of the clean-energy shift.",
      "EVs charged on renewable energy make an even bigger difference.",
      "Every charge is a small vote for a cleaner planet.",
      "Thanks for being part of the shift to electric mobility.",
    ],
    closers: [
      "Keep it up — the impact adds up fast.",
      "Thank you for driving cleaner.",
      "You're making a real difference, one charge at a time.",
      "That's a choice worth being proud of.",
      "Small actions, big collective impact.",
      "Here's to more green miles ahead.",
      "The planet says thanks.",
      "Keep charging, keep driving clean.",
      "Every trip counts.",
      "Onward to more sustainable miles.",
    ],
  },
  {
    key: "safety",
    titles: [
      "Safety First",
      "EV Safety Tip",
      "Charging Safety",
      "Stay Safe on the Road",
      "Safety Reminder",
      "Charger Safety Check",
      "Drive Safe",
      "Safety Check-In",
      "Know Before You Charge",
      "Safety Matters",
    ],
    openers: [
      "Always inspect the charging cable for damage before plugging in.",
      "Never use a charger or cable that looks worn, cracked, or frayed.",
      "Park on level, dry ground when charging outdoors during rain.",
      "Keep the charging port cover closed when not charging to keep out dust and moisture.",
      "Avoid using extension cords or adapters not made for EV charging.",
      "If a charger feels unusually hot to the touch, stop and report it.",
      "Always follow posted instructions at public charging stations.",
      "Keep children and pets away from charging cables and connectors.",
      "Check that the connector clicks securely into place before starting a session.",
      "In case of a fault light or error code, disconnect safely before troubleshooting.",
    ],
    closers: [
      "A little caution keeps every charge safe.",
      "Better safe than sorry — always.",
      "Report any issues through the app so we can fix them fast.",
      "Safety takes just a second to check.",
      "Your safety is worth the extra glance.",
      "These small checks prevent bigger problems.",
      "Stay alert, stay safe.",
      "Thanks for charging responsibly.",
      "A safe charge is a good charge.",
      "We've got your back on the road.",
    ],
  },
  {
    key: "milestone",
    titles: [
      "Milestone Unlocked",
      "You're Making Progress",
      "Charging Milestone",
      "Well Done!",
      "Look How Far You've Come",
      "Achievement Unlocked",
      "Your EV Journey",
      "Progress Update",
      "Celebrating You",
      "Milestone Alert",
    ],
    openers: [
      "You've been charging with us for a while now — thank you for being part of the journey.",
      "Every session you log helps build a smarter charging network for everyone.",
      "Your consistent charging habits are exactly what keeps your EV running its best.",
      "Looking back at your charging history, you've come a long way since your first session.",
      "You're one of the many drivers helping electric mobility grow across India.",
      "Your loyalty to electric driving hasn't gone unnoticed.",
      "Each charge you complete adds to a growing story of cleaner commutes.",
      "Thanks for trusting us to power your everyday drives.",
      "You've charged up, rolled out, and kept going — that consistency matters.",
      "From your first charge to today, you've been driving change.",
    ],
    closers: [
      "Here's to many more miles ahead.",
      "We're glad to have you with us.",
      "Keep going — you're doing great.",
      "Thank you for being part of this journey.",
      "Onward to the next milestone.",
      "We appreciate you.",
      "Cheers to your progress.",
      "More milestones await.",
      "Your journey keeps inspiring ours.",
      "Let's keep this momentum going.",
    ],
  },
  {
    key: "promo",
    titles: [
      "Limited-Time Offer",
      "Charge & Save",
      "Special for You",
      "Today's Deal",
      "Exclusive Offer",
      "Save on Your Next Charge",
      "Deal Alert",
      "Charging Discount",
      "Offer Inside",
      "Just for Our Drivers",
    ],
    openers: [
      "Check the app for special charging rates available at select stations near you.",
      "Off-peak charging hours often come with lower rates — worth checking before you plug in.",
      "Refer a friend and you could both benefit on your next charging session.",
      "Some partner stations offer discounted rates this week — take a look.",
      "New stations sometimes come with introductory offers for early users.",
      "Loyal users often get first access to new features and offers.",
      "Keep an eye on the app for limited-time charging promotions.",
      "Weekend charging deals may be live at select locations.",
      "Bundle your charging sessions and watch for savings on the app.",
      "Your next charge could cost less — check current offers in the app.",
    ],
    closers: [
      "Open the app to see what's available near you.",
      "Offers can change fast, so don't wait too long.",
      "A little savings on every charge adds up.",
      "Check it out before your next session.",
      "Good deals shouldn't be missed.",
      "See what's on offer today.",
      "Your wallet will thank you.",
      "Grab it while it's live.",
      "Every rupee saved counts.",
      "Take a look next time you charge.",
    ],
  },
  {
    key: "reminder",
    titles: [
      "Friendly Reminder",
      "Don't Forget",
      "Quick Reminder",
      "Just Checking In",
      "A Gentle Nudge",
      "Reminder",
      "Keep This in Mind",
      "Heads Up",
      "Quick Note",
      "Reminder for You",
    ],
    openers: [
      "If your battery's getting low, there's likely a charging station nearby.",
      "It's a good time to check your EV's charge level before heading out.",
      "Don't wait for the battery light — plan your next charge a little early.",
      "A quick top-up now can save you a longer wait later.",
      "Long weekend coming up? Might be a good time to plan your charging stops.",
      "Traffic can drain range faster than expected — worth checking your charge before a long drive.",
      "If you haven't charged in a few days, now's a good time to check your level.",
      "Planning a trip out of town? Map your charging stops ahead of time.",
      "It's easy to forget a charge until you need one — check now instead.",
      "Your nearest station might be closer than you think.",
    ],
    closers: [
      "Open the app to find one near you.",
      "A quick check now saves hassle later.",
      "Better to plan ahead than run low.",
      "It only takes a minute to check.",
      "Stay charged, stay ready.",
      "We're here whenever you need to charge.",
      "Plan ahead and drive worry-free.",
      "Your next charge is just a tap away.",
      "Don't let a low battery catch you off guard.",
      "A little planning goes a long way.",
    ],
  },
  {
    key: "costSaving",
    titles: [
      "Save More on Charging",
      "Smart Savings",
      "Cost-Saving Tip",
      "Charge Smart, Save More",
      "Your Wallet Will Thank You",
      "Budget-Friendly Charging",
      "Save as You Charge",
      "Money-Saving Tip",
      "Charging on a Budget",
      "Save Today",
    ],
    openers: [
      "Charging at home overnight is often cheaper than public fast charging during the day.",
      "Comparing rates across nearby stations before you charge can save you money over time.",
      "Off-peak electricity rates can make a noticeable difference on your monthly costs.",
      "Slower AC charging usually costs less per unit than rapid DC charging.",
      "Planning your charging stops in advance can help you avoid premium pricing at busy stations.",
      "Keeping your battery in the recommended range can reduce how often you need a full charge.",
      "Group charging sessions with errands to make the most of every stop.",
      "Membership or subscription plans at some networks can lower your per-session cost.",
      "Tracking your charging spend in the app can help you spot savings opportunities.",
      "Choosing the right charger speed for your need — not always the fastest — can save money.",
    ],
    closers: [
      "Every saved rupee adds up over time.",
      "Small choices make a real difference to your monthly costs.",
      "Smart charging is smart saving.",
      "Check the app to compare rates near you.",
      "A little planning goes a long way for your wallet.",
      "Saving on charging is easier than you think.",
      "Your EV should save you money, not just fuel.",
      "Keep more in your pocket with smarter charging.",
      "Every bit of savings counts.",
      "Charge smart today.",
    ],
  },
  {
    key: "community",
    titles: [
      "Join the Community",
      "EV Community Update",
      "You're Not Alone on This Road",
      "Community Spotlight",
      "Together We Charge",
      "Driving Together",
      "EV Drivers Unite",
      "Community Corner",
      "Growing Together",
      "Community News",
    ],
    openers: [
      "Thousands of EV drivers across India are charging smarter every day, just like you.",
      "Reporting a missing or broken station helps every driver in the community.",
      "Your feedback on stations helps other drivers plan better trips.",
      "The EV community is growing fast — thanks for being an early part of it.",
      "Sharing your charging experience helps build a more reliable network for everyone.",
      "Every review and report you leave makes the map more accurate for the next driver.",
      "You're part of a growing movement of drivers choosing cleaner commutes.",
      "Word of mouth from drivers like you helps others discover new stations.",
      "The more drivers report issues, the faster stations get fixed.",
      "Together, EV drivers are shaping how India charges.",
    ],
    closers: [
      "Thanks for being part of it.",
      "Every contribution helps the whole community.",
      "We're building this together.",
      "Your voice matters here.",
      "Keep sharing, keep helping.",
      "The community grows stronger with you in it.",
      "Thanks for driving this forward with us.",
      "Small contributions, big collective change.",
      "We appreciate every report and review.",
      "Here's to a stronger charging network.",
    ],
  },
  {
    key: "newStation",
    titles: [
      "New Station Alert",
      "Fresh Charging Spot",
      "Just Added Near You",
      "New on the Map",
      "Charging Network Update",
      "New Station Nearby",
      "Just Opened",
      "Expanding Our Network",
      "New Spot to Charge",
      "Network Update",
    ],
    openers: [
      "New charging stations are being added to the map regularly — check what's near you.",
      "Our charging network keeps growing, with new stations added across the country.",
      "A new station may have just opened up along your usual route.",
      "More stations mean shorter waits and more convenient charging stops.",
      "Keep the app updated to see the newest stations as they go live.",
      "New locations often come with fresh, well-maintained chargers.",
      "Your next commute might have a new charging option along the way.",
      "The map is refreshed often — worth a quick look before your next trip.",
      "New stations are chosen based on where drivers need them most.",
      "Discovering a new nearby station could make your next charge easier.",
    ],
    closers: [
      "Open the app to see what's new near you.",
      "More options mean more convenience for you.",
      "Check the map before your next drive.",
      "New stations, same reliable charging.",
      "We're always expanding to serve you better.",
      "Take a look and plan your next stop.",
      "Convenience is just an update away.",
      "Explore what's new on the map.",
      "Your next charge could be closer than before.",
      "Keep exploring the growing network.",
    ],
  },
  {
    key: "seasonal",
    titles: [
      "Seasonal Charging Tip",
      "Weather Watch",
      "Monsoon Reminder",
      "Summer Charging Tip",
      "Winter EV Care",
      "Season Check-In",
      "Weather-Ready Charging",
      "Seasonal Reminder",
      "Prepare for the Season",
      "Weather Wise",
    ],
    openers: [
      "Hot weather can affect battery performance — try charging in shade when you can.",
      "During monsoon season, make sure connectors are dry before plugging in.",
      "Cooler temperatures can slightly reduce range — plan a little extra charge in winter.",
      "Heavy rains are a good reason to double-check your charging point's cover and seals.",
      "Summer road trips are more fun with charging stops planned ahead of time.",
      "As temperatures shift, your EV's range may vary a little — keep an eye on it.",
      "Festive season travel means busier roads and busier charging stations — plan early.",
      "Long holiday drives are smoother with a full charge and a mapped-out route.",
      "Extreme heat or cold both call for a bit of extra care with your battery.",
      "Seasonal weather changes are a good time to review your usual charging routine.",
    ],
    closers: [
      "A little seasonal care goes a long way.",
      "Stay prepared, whatever the weather.",
      "Plan ahead and drive worry-free this season.",
      "Small adjustments keep your EV running smoothly.",
      "Weather changes, but reliable charging shouldn't.",
      "Here's to smooth, well-charged journeys.",
      "Stay safe and stay charged this season.",
      "A well-timed charge beats a weather surprise.",
      "Prepare now, drive easy later.",
      "Enjoy the season, fully charged.",
    ],
  },
];

const NOTIFICATION_TEMPLATES = [];

for (const category of CATEGORIES) {
  category.openers.forEach((opener, openerIndex) => {
    category.closers.forEach((closer, closerIndex) => {
      const title = category.titles[(openerIndex + closerIndex) % category.titles.length];
      NOTIFICATION_TEMPLATES.push({
        category: category.key,
        title,
        body: `${opener} ${closer}`,
      });
    });
  });
}

module.exports = NOTIFICATION_TEMPLATES;
